import { MongoClient, ObjectId } from "mongodb"
import { generateSearchText, getEmbedding } from "@/lib/embeddings"

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017"
const DB_NAME = "b2b_marketplace"

async function seed() {
    const client = new MongoClient(MONGODB_URI)
    try {
        await client.connect()
        const db = client.db(DB_NAME)
        await db.collection("categories").deleteMany({})
        await db.collection("listings").deleteMany({})
        const categories = [
            {
                _id: new ObjectId(),
                name: "Televisions",
                slug: "televisions",
                attributeSchema: [
                    { name: "brand", type: "string", required: false },
                    { name: "screenSize", type: "string", required: false },
                    { name: "resolution", type: "string", required: false },
                    { name: "smartTV", type: "boolean", required: false },
                    { name: "displayType", type: "string", required: false },
                    { name: "color", type: "string", required: false },
                    { name: "condition", type: "string", required: false },
                ],
            },
            {
                _id: new ObjectId(),
                name: "Running Shoes",
                slug: "running-shoes",
                attributeSchema: [
                    { name: "brand", type: "string", required: false },
                    { name: "size", type: "string", required: false },
                    { name: "color", type: "string", required: false },
                    { name: "gender", type: "string", required: false },
                    { name: "material", type: "string", required: false },
                    { name: "style", type: "string", required: false },
                    { name: "condition", type: "string", required: false },
                ],
            },
        ]
        await db.collection("categories").insertMany(categories)
        console.log("Created categories")
        const listings = [
            {
                title: "Samsung 55\" 4K Smart TV - QLED",
                description: "Samsung QLED 55-inch smart TV with Quantum HDR. Ideal for corporate boardrooms.",
                price: 85000,
                location: "Mumbai, MH",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Samsung",
                    screenSize: "55\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "QLED",
                    color: "Titanium Gray",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "LG 65\" OLED C3 Display",
                description: "LG OLED C3 with infinite contrast. Perfect for luxury retail displays.",
                price: 145000,
                location: "Delhi, DL",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "LG",
                    screenSize: "65\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "OLED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Sony 43\" Bravia XR Monitor",
                description: "Sony Bravia XR with accurate colors. Suitable for design studios.",
                price: 65000,
                location: "Bengaluru, KA",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Sony",
                    screenSize: "43\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "LED",
                    color: "Black",
                    condition: "Refurbished",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "TCL 50\" 6-Series Mini-LED TV",
                description: "TCL Mini-LED with Quantum Dot technology for budget-conscious offices.",
                price: 45000,
                location: "Chennai, TN",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "TCL",
                    screenSize: "50\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "Mini-LED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Hisense 32\" A6G Smart TV",
                description: "Compact Hisense A6G for small offices and hotel rooms.",
                price: 18000,
                location: "Hyderabad, TS",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Hisense",
                    screenSize: "32\"",
                    resolution: "Full HD",
                    smartTV: true,
                    displayType: "LED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Philips 48\" OLED Display",
                description: "Philips OLED with Ambilight for upscale retail environments.",
                price: 110000,
                location: "Pune, MH",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Philips",
                    screenSize: "48\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "OLED",
                    color: "Silver",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Vizio 75\" P-Series Quantum X",
                description: "Large Vizio P-Series for conference rooms and auditoriums.",
                price: 95000,
                location: "Ahmedabad, GJ",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Vizio",
                    screenSize: "75\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "QLED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Samsung 85\" Crystal UHD TV",
                description: "Massive Samsung Crystal UHD for corporate presentations.",
                price: 140000,
                location: "Kolkata, WB",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Samsung",
                    screenSize: "85\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "LED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "LG 40\" UltraFine Monitor",
                description: "LG UltraFine with USB-C for design studios, excellent condition.",
                price: 35000,
                location: "Bengaluru, KA",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "LG",
                    screenSize: "40\"",
                    resolution: "4K",
                    smartTV: false,
                    displayType: "IPS LCD",
                    color: "White",
                    condition: "Used - Excellent",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Sony 77\" A95K QD-OLED TV",
                description: "Premium Sony QD-OLED for luxury corporate environments.",
                price: 250000,
                location: "Mumbai, MH",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Sony",
                    screenSize: "77\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "QD-OLED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "TCL 32\" 3-Series Roku TV",
                description: "TCL Roku TV for employee lounges, refurbished.",
                price: 12000,
                location: "Delhi, DL",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "TCL",
                    screenSize: "32\"",
                    resolution: "Full HD",
                    smartTV: true,
                    displayType: "LED",
                    color: "Black",
                    condition: "Refurbished",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Hisense 58\" U8H ULED TV",
                description: "Hisense U8H with Quantum Dot for corporate meeting rooms.",
                price: 55000,
                location: "Chennai, TN",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Hisense",
                    screenSize: "58\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "ULED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Philips 65\" 7000 Series Android TV",
                description: "Philips Android TV with Ambilight for modern offices.",
                price: 75000,
                location: "Hyderabad, TS",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Philips",
                    screenSize: "65\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "LED",
                    color: "Dark Silver",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Vizio 43\" D-Series Smart TV",
                description: "Vizio D-Series for cost-effective multi-room installations.",
                price: 20000,
                location: "Pune, MH",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Vizio",
                    screenSize: "43\"",
                    resolution: "Full HD",
                    smartTV: true,
                    displayType: "LED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Samsung 98\" The Wall MicroLED",
                description: "Samsung The Wall MicroLED for executive boardrooms.",
                price: 1000000,
                location: "Mumbai, MH",
                categoryId: categories[0]._id,
                attributes: {
                    brand: "Samsung",
                    screenSize: "98\"",
                    resolution: "4K",
                    smartTV: true,
                    displayType: "MicroLED",
                    color: "Black",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Nike Air Max 270",
                description: "Nike Air Max 270 for corporate wellness programs.",
                price: 7500,
                location: "Bengaluru, KA",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Nike",
                    size: "Various (6-13)",
                    color: "Black/White",
                    gender: "Unisex",
                    material: "Mesh/Synthetic",
                    style: "Running/Lifestyle",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Adidas Ultraboost 23",
                description: "Adidas Ultraboost for executive corporate gifting.",
                price: 12000,
                location: "Delhi, DL",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Adidas",
                    size: "Various (5-14)",
                    color: "Core Black/Solar Yellow",
                    gender: "Unisex",
                    material: "Primeknit Upper",
                    style: "Performance Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "New Balance 990v5",
                description: "New Balance 990v5 for corporate uniform programs.",
                price: 11000,
                location: "Mumbai, MH",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "New Balance",
                    size: "Various (6-15)",
                    color: "Grey/White",
                    gender: "Unisex",
                    material: "Suede/Mesh",
                    style: "Lifestyle/Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "ASICS Gel-Kayano 30",
                description: "ASICS Gel-Kayano 30 for healthcare professionals.",
                price: 9500,
                location: "Chennai, TN",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "ASICS",
                    size: "Various (5-13)",
                    color: "Midnight/Electric Blue",
                    gender: "Unisex",
                    material: "Engineered Mesh/FF Blast Plus",
                    style: "Stability Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Brooks Ghost 16",
                description: "Brooks Ghost 16 for corporate wellness initiatives.",
                price: 8500,
                location: "Hyderabad, TS",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Brooks",
                    size: "Various (6-14)",
                    color: "Peacoat/Blue/Orange",
                    gender: "Men's",
                    material: "Engineered Air Mesh",
                    style: "Neutral Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Puma Velocity Nitro 3",
                description: "Puma Velocity Nitro 3 for creative agencies.",
                price: 6500,
                location: "Pune, MH",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Puma",
                    size: "Various (5-12)",
                    color: "PUMA White/PUMA Black",
                    gender: "Unisex",
                    material: "Engineered Mesh/NITRO Foam",
                    style: "Neutral Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Under Armour HOVR Phantom 3",
                description: "Under Armour HOVR for tech-forward companies.",
                price: 10000,
                location: "Bengaluru, KA",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Under Armour",
                    size: "Various (6-13)",
                    color: "Black/White/Halo Gray",
                    gender: "Men's",
                    material: "Engineered Spacer Mesh",
                    style: "Neutral Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Hoka Clifton 9",
                description: "Hoka Clifton 9 for long-shift comfort.",
                price: 9000,
                location: "Delhi, DL",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Hoka",
                    size: "Various (5-14)",
                    color: "Black/Black",
                    gender: "Unisex",
                    material: "Engineered Knit/EVA Midsole",
                    style: "Max Cushion Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Saucony Triumph 21",
                description: "Saucony Triumph 21 for premium corporate packages.",
                price: 10500,
                location: "Mumbai, MH",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Saucony",
                    size: "Various (6-13)",
                    color: "Charcoal/Orange",
                    gender: "Men's",
                    material: "Engineered Mesh/PWRRUN+",
                    style: "Max Cushion Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Mizuno Wave Rider 27",
                description: "Mizuno Wave Rider 27 for quality-focused orders.",
                price: 8000,
                location: "Chennai, TN",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Mizuno",
                    size: "Various (6-12)",
                    color: "Black/White/Orange",
                    gender: "Unisex",
                    material: "AIRmesh/ENERZY",
                    style: "Neutral Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Nike Pegasus 40 Women's",
                description: "Nike Pegasus 40 for women's corporate wellness.",
                price: 7500,
                location: "Bengaluru, KA",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Nike",
                    size: "Women's 5-12",
                    color: "Pure Platinum/Pink Foam",
                    gender: "Women's",
                    material: "Engineered Mesh/React Foam",
                    style: "Daily Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Adidas Solar Glide 6",
                description: "Adidas Solar Glide 6 with recycled materials.",
                price: 7000,
                location: "Delhi, DL",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Adidas",
                    size: "Various (6-13)",
                    color: "Core Black/Solar Red",
                    gender: "Men's",
                    material: "Recycled Polyester/Boost",
                    style: "Long Distance Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "New Balance Fresh Foam X 1080v13",
                description: "New Balance 1080v13 for executive wellness programs.",
                price: 11500,
                location: "Mumbai, MH",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "New Balance",
                    size: "Various (6-14)",
                    color: "Black/Thunder/Lemon Slush",
                    gender: "Unisex",
                    material: "Hypoknit/Fresh Foam X",
                    style: "Max Cushion Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "ASICS Gel-Nimbus 26",
                description: "ASICS Gel-Nimbus 26 for luxury corporate gifting.",
                price: 12000,
                location: "Chennai, TN",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "ASICS",
                    size: "Various (5-13)",
                    color: "Black/Pure Silver",
                    gender: "Unisex",
                    material: "Engineered Knit/FF Blast Plus Eco",
                    style: "Max Cushion Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                title: "Brooks Glycerin 21 Women's",
                description: "Brooks Glycerin 21 for women executives.",
                price: 10500,
                location: "Hyderabad, TS",
                categoryId: categories[1]._id,
                attributes: {
                    brand: "Brooks",
                    size: "Women's 5-12",
                    color: "Purple/Lavender/White",
                    gender: "Women's",
                    material: "Engineered Air Mesh/DNA Loft v3",
                    style: "Max Cushion Running",
                    condition: "New",
                },
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]
        const allListings = [...listings,]

        console.log("Generating embeddings for listings...")

        for (let i = 0; i < allListings.length; i++) {
            const listing = allListings[i]

            try {
                const searchText = generateSearchText({
                    title: listing.title,
                    description: listing.description,
                    location: listing.location,
                    attributes: listing.attributes,
                })

                const embedding = await getEmbedding(searchText)

                allListings[i] = {
                    ...listing,
                    embedding,
                    searchText,
                }

                console.log(`Generated embedding ${i + 1}/${allListings.length}: ${listing.title}`)
            } catch (error) {
                console.error(`Failed to generate embedding for: ${listing.title}`, error)
            }
        }

        console.log("Embeddings generation completed!")

        await db.collection("listings").insertMany(allListings)

        await db.collection("listings").createIndex({
            title: "text",
            description: "text",
        })

        console.log(`Created ${allListings.length} sample listings`)
        console.log("Created text index for search")
        console.log("Seeding completed successfully!")
    } catch (error) {
        console.error("Seeding failed:", error)
    } finally {
        await client.close()
    }
}

seed()